CREATE DATABASE IF NOT EXISTS app_db;
# CREATE USER IF NOT EXISTS 'app_user'@'localhost' IDENTIFIED BY 'StrongPassword123!';
# GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'localhost';
# FLUSH PRIVILEGES;

USE app_db;
CREATE TABLE IF NOT EXISTS demo_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
